
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  app:
      container_name: server
      restart: always
    
      volumes:
      - ./src:/app/src
      develop:
        watch:
          - action: rebuild
            path: ./src    
      build:    
        context: .
      depends_on:
      - postgres
      networks:
      - prisma-network
      ports: 
      - "${PORT}:${PORT}" 

networks:
  prisma-network:
    driver: bridge

volumes:
  postgres_data: